apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mapproxy.fullname" . }}
  labels:
    {{- include "mapproxy.labels" . | nindent 4 }}
data:
  app.py: |-
    # WSGI module for use with Apache mod_wsgi or gunicorn
    import os
    from mapproxy.wsgiapp import make_wsgi_app
    application = make_wsgi_app(os.getenv('UWSGI_PYARGV'), reloader=True)
  mapproxy.yaml: |-
    # -------------------------------
    # MapProxy configuration.
    #
    # OSM example based on https://wiki.openstreetmap.org/wiki/MapProxy
    # -------------------------------
    services:
      demo:
      wmts:
        restful: true

    layers:
      - name: osm-terrestris
        title: OpenStreetMap WMS by terrestris
        sources: [osm_terrestris_cache]

    caches:
      osm_terrestris_cache:
        sources: [osm_terrestris]
        grids: [osm_terrestris_grid]
        format: image/png
        cache:
          type: sqlite
          directory: /srv/mapproxy/cache_data/osm_terrestris_cache

    sources:
      osm_terrestris:
        type: wms
        req:
          url: https://ows.terrestris.de/osm/service
          transparent: true
          layers: OSM-WMS

    grids:
      osm_terrestris_grid:
        srs: EPSG:3857
        origin: nw

    globals:
      cache:
        base_dir: '/srv/mapproxy/cache_data'
        lock_dir: '/srv/mapproxy/cache_data/locks'
        tile_lock_dir: '/srv/mapproxy/cache_data/tile_locks'

    image:
      resampling_method: bicubic
  seed.yaml: |-
    seeds:
      osm_terrestris_cache:
        caches: [osm_terrestris_cache]
        refresh_before:
          weeks: 1
  uwsgi.conf: |-
    [uwsgi]
    master = true
    chdir = $(UWSGI_CHDIR)
    pyargv = $(UWSGI_PYARGV)
    wsgi-file = $(UWSGI_WSGI_FILE)
    pidfile=/tmp/mapproxy.pid
    socket = /tmp/uwsgi.sock
    processes = $(UWSGI_PROCESSES)
    threads = $(UWSGI_THREADS)
    chmod-socket = 777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mapproxy.fullname" . }}-nginx
  labels:
    {{- include "mapproxy.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
        listen 80;

        root /var/www/html/;

        location /mapproxy/ {
            rewrite /mapproxy/(.+) /$1 break;
            uwsgi_param SCRIPT_NAME /mapproxy;
            uwsgi_pass unix:///tmp/uwsgi.sock;
            include uwsgi_params;
        }
    }
