# Default values for postgis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.terrestris.de/postgis/postgis
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgres:
  user: postgres
  password: postgres
  customInit:
    enabled: false
#    user: my_user
#    password: my_password
#    databases:
#      - my_database

persistence:
  size: 8Gi
