replicaCount: 1

image:
  repository: terrestris/geoserver
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  ingressClassName: traefik
  enabled: true
  hosts:
    - host: geoserver2.dev.networkoverview.vodafone.de
      paths:  
        - path: "/geoserver"
          pathType: ImplementationSpecific
resources:
  limits:
    cpu: 2
    memory: 3Gi
  requests:
    cpu: 100m
    memory: 1Gi

#  nodegroup: geoserver

tolerations:
  - effect: NoSchedule
    key: node
    operator: Equal
    value: geoserver

#affinity: 
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: nodegroup
#          operator: In
#          values:
#          - geoserver

environment:
  # installExtensions: "true"
  # stableExtensions: css,querylayer
  # replace example.com with your host
  javaOptions: -Xms1g -Xmx2g -DGEOSERVER_CSRF_WHITELIST=localhost,example.com

storage:
  dataDir: /opt/geoserver_data
  additionalLibsDir: /opt/additional_libs
  # initDataUrl: https://files.example.com/geoserver_data.tgz

# optional existing pvc for persistent geoserver data
persistence:
  enabled: true
  useExisting: false
  existingPvcName: ""
  storageClassName: "gp2"
  accessMode: ReadWriteOnce
  size: 8Gi

probes:
  livenessUrl: /geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png
  readinessUrl: /geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png

# extraEnv: |
#   - name: QUERY_LAYER_MAX_FEATURES
#     value: 100000

# extraEnvFrom: |
#   - secretRef:
#       name: '{{ include "geoserver.fullname" . }}-secret'
